blank_issues_enabled: false
contact_links:
  - name: ğŸ’Š ä½¿ç”¨é—®é¢˜
    url: https://jq.qq.com/?_wv=1027&k=iL4Gr1Oe
    about: å½“ä½ è§‰å¾— è¿™ç©æ„æˆ‘æä¸æ‡‚æ€ä¹ˆç”¨/å®ƒæ²¡ååº”/å®ƒæŠ¥é”™äº†ä½†æ˜¯æˆ‘ä¸ç¡®å®šæ˜¯ä¸æ˜¯BUG çš„æ—¶å€™ç‚¹è¿™ä¸ª